from card import Card, AfterPowerCard, TurnPowerCard
from color import Color
from effect import BanElementEffect
from effect import DiscardOneColorEffect, DiscardElementEffect
from effect import ReversalTurnEffect, SwapElementsTurnEffect
from effect import Plus2Effect, Minus2Effect
from effect import TurnEffect, AfterEffect
from element import Element

standard_deck = [
    Card(Color.BLUE, Element.FIRE, 3),
    Card(Color.GREEN, Element.FIRE, 2),
    Card(Color.GREEN, Element.FIRE, 8),
    Card(Color.ORANGE, Element.FIRE, 3),
    Card(Color.PURPLE, Element.FIRE, 4),
    Card(Color.PURPLE, Element.FIRE, 6),
    Card(Color.RED, Element.FIRE, 2),
    Card(Color.RED, Element.FIRE, 7),
    Card(Color.YELLOW, Element.FIRE, 2),
    Card(Color.YELLOW, Element.FIRE, 5),
    Card(Color.BLUE, Element.SNOW, 3),
    Card(Color.GREEN, Element.SNOW, 2),
    Card(Color.GREEN, Element.SNOW, 5),
    Card(Color.ORANGE, Element.SNOW, 3),
    Card(Color.PURPLE, Element.SNOW, 4),
    Card(Color.PURPLE, Element.SNOW, 8),
    Card(Color.RED, Element.SNOW, 2),
    Card(Color.RED, Element.SNOW, 6),
    Card(Color.YELLOW, Element.SNOW, 2),
    Card(Color.YELLOW, Element.SNOW, 7),
    Card(Color.BLUE, Element.WATER, 3),
    Card(Color.BLUE, Element.WATER, 5),
    Card(Color.GREEN, Element.WATER, 2),
    Card(Color.GREEN, Element.WATER, 8),
    Card(Color.ORANGE, Element.WATER, 3),
    Card(Color.PURPLE, Element.WATER, 4),
    Card(Color.PURPLE, Element.WATER, 6),
    Card(Color.RED, Element.WATER, 2),
    Card(Color.RED, Element.WATER, 7),
    Card(Color.YELLOW, Element.WATER, 2),
    AfterPowerCard(Color.RED, Element.FIRE, 9, BanElementEffect(Element.SNOW)),
    TurnPowerCard(Color.BLUE, Element.FIRE, 9, SwapElementsTurnEffect(Element.WATER, Element.FIRE)),
    TurnPowerCard(Color.YELLOW, Element.FIRE, 10, ReversalTurnEffect()),
    AfterPowerCard(Color.ORANGE, Element.FIRE, 10, DiscardElementEffect(Element.SNOW)),
    AfterPowerCard(Color.PURPLE, Element.FIRE, 11, DiscardOneColorEffect(Color.RED)),
    AfterPowerCard(Color.GREEN, Element.FIRE, 11, DiscardOneColorEffect(Color.YELLOW)),
    AfterPowerCard(Color.RED, Element.FIRE, 12, Plus2Effect()),
    AfterPowerCard(Color.BLUE, Element.FIRE, 12, Minus2Effect()),
    AfterPowerCard(Color.RED, Element.SNOW, 9, BanElementEffect(Element.WATER)),
    TurnPowerCard(Color.BLUE, Element.SNOW, 9, SwapElementsTurnEffect(Element.FIRE, Element.SNOW)),
    TurnPowerCard(Color.GREEN, Element.SNOW, 10, ReversalTurnEffect()),
    AfterPowerCard(Color.GREEN, Element.SNOW, 10, DiscardElementEffect(Element.WATER)),
    AfterPowerCard(Color.PURPLE, Element.SNOW, 11, DiscardOneColorEffect(Color.GREEN)),
    AfterPowerCard(Color.YELLOW, Element.SNOW, 11, DiscardOneColorEffect(Color.PURPLE)),
    AfterPowerCard(Color.ORANGE, Element.SNOW, 12, Plus2Effect()),
    AfterPowerCard(Color.ORANGE, Element.SNOW, 12, Minus2Effect()),
    AfterPowerCard(Color.RED, Element.WATER, 9, BanElementEffect(Element.FIRE)),
    TurnPowerCard(Color.BLUE, Element.WATER, 9, SwapElementsTurnEffect(Element.SNOW, Element.WATER)),
    TurnPowerCard(Color.YELLOW, Element.WATER, 10, ReversalTurnEffect()),
    AfterPowerCard(Color.ORANGE, Element.WATER, 10, DiscardElementEffect(Element.FIRE)),
    AfterPowerCard(Color.PURPLE, Element.WATER, 11, DiscardOneColorEffect(Color.BLUE)),
    AfterPowerCard(Color.GREEN, Element.WATER, 11, DiscardOneColorEffect(Color.ORANGE)),
    AfterPowerCard(Color.PURPLE, Element.WATER, 12, Plus2Effect()),
    AfterPowerCard(Color.YELLOW, Element.WATER, 12, Minus2Effect()),
]